### PR TITLE
Do not throw an NPE during opening the main screen

### PR DESCRIPTION
**Pull request by gzsombor**
when there is no network available.
In that case the "videosList" is null.

### CODE REVIEW

**Comment by okan35** [comment]
Hi @gzsombor I actually fixed it in connection check pull request sometime ago.

**Comment by gzsombor** [comment]
Interesting, I saw it yesterday, when I tried to fix problems with downloads list is not refreshed

**Comment by okan35** [comment]
It is because it has not been ready for merge so ram-on has not done it yet. There are just small fixes I should do in the commit but could not do it for some time. Hopefully will finish it.

**Comment by gzsombor** [comment]
Ohh, I see :)

**Comment by ram-on** [comment]
Thanks

**Pull request merged**
