### PR TITLE
Add scroll to top of list when clicking on current tab

### PR DESCRIPTION
**Pull request by Tvax**

### CODE REVIEW

**Comment by gzsombor** [comment]
Thanks for the patch, interesting idea. I would never thought about clicking the current tab without any clue that it will do something, but this could be convenient. What do you think @atomjack ?

**Comment by Tvax** [comment]
A lot of Android fediverse apps have these feature. Plus, if I remember correctly the Android YouTube app has it too.

**Comment by atomjack** [comment]
Yeah that's great!!

**Comment by gzsombor** [comment]
Thanks, I learn something new, everyday:)

**Pull request merged**
