### PR TITLE
Added swipe controls

### PR DESCRIPTION
**Pull request by avently**
- allowed to change brightness and volume via vertical swipe
- seek video is supported too via horizontal swipe
- brightness is saved across restarts in sharedPreferences and will be applied automatically on video load
- cool vector icons for all screens

Found time and made a normal PR with less code than before and adapted to current code base.

### CODE REVIEW

**Comment by ram-on** [comment]
Hi @avently, I'll test it out this weekend and I'll get back to you.

**Comment by ildar** [comment]
@avently , great to see you implementing this essential feature!
Could you please note that the scale for the three should better be
exponential rather then linear? Maybe better fixing it now rather then
later getting to it again?
Thanks again!
P.S. maybe leaving brightness linear, but volume and seek definitely
exponential...

**Comment by avently** [comment]
@ildar you mean you want to skip more than a minute via one swipe? For example,  first 10% of the screen width will skip 20 seconds,  20% will skip 1 minute, then 2 minutes, 5 minutes, etc?

**Comment by atomjack** [comment]
Well done, @avently !! Looks great!!

**Comment by ildar** [comment]
Yes, you got it right. As in vlc and such.

**Comment by avently** [comment]
@ildar now it's a little bit cooler

**Comment by ildar** [comment]
Awesome! :)

**Comment by ram-on** [comment]
Hello @avently, thanks for your implementation - looks great.  The following is my feedback:

1. Methods inside OnSwipeTouchListener that do not have any code should be changed to abstract.
1. `OnSwipeTouchListener#viewRect()` should be changed to private and to abstract.  Also add comments on what it does.
1. What does `onGestureDone()` do?  Also the parameter notStart is not being used - so we should remove that.
1. Add (javadoc) comments (i.e. `/** ... */`) to each method and explain what each parameter does.
1. For `adjustBrightness()` and `adjustVolumeLevel()` inside YouTubePlayerFragment:  Pls add comments describing the major actions taking place.
1. `YouTubePlayerFragment#formatDuration()`:  This can be changed to private and pls remove the static keyword.

**Comment by avently** [comment]
Hello @ram-on 
OnSwipeTouchListener#viewRect() is important. It can't be changed to private static. It returns actual frame of the view that overrides this method. I can't get actual rect from touchListener without it. 

Other is done.

**Comment by ram-on** [comment]
Looks good. Thanks

**Pull request merged**
