### PR TITLE
Check if the current network is metered.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
Check whether or not the current network is metered instead of checking if it is a mobile network.

### CODE REVIEW

**Comment by gzsombor** [comment]
Thanks for the patch. I only have two concerns:
* As the translations are handled by weblate ( https://hosted.weblate.org/git/skytube/strings/ ), if we just rename the keys/values no translator would notice, that the original text have been changed. Maybe, we can introduce new keys/translations, and use a fallback, if no translation found. But I think, I'm a bit over complicating our life's. :thinking: 
* Adding migration to this settings could be nice: https://github.com/ram-on/SkyTube/blob/f3e2392f63d663af03fe59a42af5804f945aa276/app/src/main/java/free/rm/skytube/app/Settings.java#L50

**Comment by Isira-Seneviratne** [comment]
> Thanks for the patch. I only have two concerns:
> 
> * As the translations are handled by weblate ( https://hosted.weblate.org/git/skytube/strings/ ), if we just rename the keys/values no translator would notice, that the original text have been changed. Maybe, we can introduce new keys/translations, and use a fallback, if no translation found. But I think, I'm a bit over complicating our life's. 🤔

In that case, shall I revert the key name changes?

**Comment by gzsombor** [comment]
I think, the simplest thing is to only modify the English text and the keys, and the translator can freely decide, what is the appropriate translations.

**Comment by gzsombor** [comment]
Thanks for the patch,  I've rebased and merged it!

**Pull request closed without merging**
