### PR TITLE
Spelling: Channel information, - found

### PR DESCRIPTION
**Pull request by comradekingu**
Like "map info"
Alternatively, "information about channels"
Found was just redundant

### CODE REVIEW

**Comment by ram-on** [comment]
Hello @comradekingu.  Regarding "Fetching channels's information…" this actually should be "Fetching channels' information…".  My mistake.  I personally do not like "Fetching information about channels"... it is too long.  Unless you have another suggestion?

> Found was just redundant
I agree.

**Comment by comradekingu** [comment]
@ram-on You can fetch channel information from one or multiple channels. Your above statement is unclear as to what you think about this.
If you describe exactly what happens, maybe I could come up with something better.

**Comment by ram-on** [comment]
@comradekingu its aim is to inform the user that the app is currently fetching information about channel**s**.

**Comment by comradekingu** [comment]
@ram-on It is "channel information" plural too. It is the _concept_ that is conveyed, not the subject of channel plural.

**Pull request merged**
