### PR TITLE
channels are sorted alphabetically

### PR DESCRIPTION
**Pull request by okan35**
Hi @ram-on I added a method to SubsAdapter to sort channels. I tried it by importing channels from youtube subscriptions, by subscribing and unsubscribing. It looks like it is working fine. 

By doing this in SubsAdapter, I did not need to do any sorting in `SubscriptionsDb` or `GetYoutubeChannelsTask`.

### CODE REVIEW

**Comment by ram-on** [comment]
Hi @okan35.  This is not working.  You need to move the `sortChannelsAlphabetically()` from the `SubsAdapter` to `GetSubscribedChannelsTask`.

Also add a preference options in the preferences for users to enable such functionality.

**Comment by okan35** [comment]
@ram-on I don't understand how it is not working because I just tried again and it is working totally as it should. If I move move the `sortChannelsAlphabetically()` from the SubsAdapter to `GetSubscribedChannelsTask`, it works for importing channels from youtube xml file to subscripton drawer but it does not work when you subscribe to a channel.

But If I put it in `SubsAdapter#getSubsList()` it works when user subscribes and unsubscribes and imports channels from youtube. I can put a gif video if you want.

**Comment by ram-on** [comment]
Hi @okan35.  My bad, it is indeed working!

Can you pls add an option in the Preferences for users to enable or disable this feature?

**Comment by okan35** [comment]
Hopefully I will finish that part today, I already made the necessary changes in layout.

**Comment by okan35** [comment]
@ram-on now you can check it. Although in my opinion this feature should be default as it looks much better when channels are in a order, so in my opinion there is no need for option to choose. But still did it, hope it is done :)

**Comment by ram-on** [comment]
Hi @okan35 I've found 2 bugs:

**Bug 1:**
1. Subscribe to a number of channels
1. Enable the "Sort channels alphabetically" preference option
1. Go to the main activity and open the subscriptions list.  The channels are not sorted.

**Bug 2:**
1.  Ensure that the "Sort channels alphabetically" preference option is enabled.
2. Close the app
3. Reopen the app
4. The channels are still not sorted.

**Comment by okan35** [comment]
@ram-on both are fixed. I tried what you did in both bugs, seems fixed to me. please let me know.

**Comment by ram-on** [comment]
It's working great.  Thank

**Comment by ram-on** [comment]
@okan35 I've just noticed this bug:
1. set the option to sort the channels
1. close the app
1. open the app
1. channels are not sorted.

Can you fix it?

**Comment by okan35** [comment]
@ram-on I tried several times but I can't get that bug.

Trial 1: subscribe some channels - check sort channels - directly close the app - open the app. 

Channels are still sorted as it must be because the sorting is directly done under that fragment which is ensured by shared preferences.

Trial 2: same way but after checking sort channels option , I checked subscription drawer to see situation which was fine then closed the app, opened the app they were still sorted. 

By the way I did these tests after cleaning the data of the app.

**Comment by ram-on** [comment]
@okan35 I've retested it on a clean build.  The above bug is reproducible - maybe you've forgot to commit some code?  I'm going to open an issue jut for the sake of keeping things in track.

**Pull request merged**
