### PR TITLE
Channel blocking

### PR DESCRIPTION
**Pull request by okan35**
Requested changes are done for a better blocking feature.

### CODE REVIEW

**Comment by ram-on** [comment]
@okan35, there is a small issue which can be reproduced as follows:
1. Go to preferences
1. Tap on "Blocked Channels" > Unblock a channel (say 'channel_a')
1. If you re-tap on "Blocked Channels", you can see that channel_a is still there (it should not be there as it has just been unblocked).

**Comment by okan35** [comment]
@ram-on Yeah that I know. That is why I tell user to refresh main page so that unblocked channel won't be seen there. But I will try to do it the way you said.

**Comment by ram-on** [comment]
> That is why I tell user to refresh main page so that unblocked channel won't be seen there. But I will try to do it the way you said.

What I meant is that when you close the blocked channels popup (multiSelectListPreference) and then you immediately reopen it, the list of blocked channels is not updated.

**Comment by okan35** [comment]
Yeah I got it now that it is not updating, I am working on it now.

**Comment by ram-on** [comment]
Try to get an updated list of blocked channels when OnPreferenceChangeListener is called and then set it, similar to this:

```
multiSelectListPreference.setOnPreferenceChangeListener(new Preference.OnPreferenceChangeListener() {
    @Override
    public boolean onPreferenceChange(Preference preference, Object o) {
        // ...
        multiSelectListPreference.setEntries( getBlockedChannels() );
        // ...
    }
});

// ...
private String[] getBlockedChannels() {
    final BlockedChannelsDb blockedChannelsDb = BlockedChannelsDb.getBlockedChannelsDb();
    return blockedChannelsDb.getBlockedChannelsListName().
                toArray(new String[blockedChannelsDb.getBlockedChannelsListName().size()]);
}
```

**Comment by okan35** [comment]
Hey @ram-on, I have also tried what you said. It seems it is not working totally. Here you can see the code.  It sometimes works sometimes does not. 

```java
@Override
    public void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        addPreferencesFromResource(R.xml.preference_blocked_channels);
        final MultiSelectListPreference multiSelectListPreference = (MultiSelectListPreference) findPreference(getString(R.string.pref_blocked_channels_list_key));

        final BlockedChannelsDb blockedChannelsDb = BlockedChannelsDb.getBlockedChannelsDb();

        String[] blockedChannelsName = blockedChannelsDb.getBlockedChannelsListName().
                toArray(new String[blockedChannelsDb.getBlockedChannelsListName().size()]);

        multiSelectListPreference.setEntries(blockedChannelsName);
        multiSelectListPreference.setEntryValues(blockedChannelsName);
        multiSelectListPreference.setPositiveButtonText(R.string.unblock_button);

        multiSelectListPreference.setOnPreferenceClickListener(new Preference.OnPreferenceClickListener() {
            @Override
            public boolean onPreferenceClick(Preference preference) {
                if (blockedChannelsDb.getBlockedChannelsListName().isEmpty()) {
                    Toast.makeText(getActivity(), "There is not any blocked channel.", Toast.LENGTH_SHORT).show();
                }
                return true;
            }
        });

        multiSelectListPreference.setOnPreferenceChangeListener(new Preference.OnPreferenceChangeListener() {
            @Override
            public boolean onPreferenceChange(Preference preference, Object o) {
                //sets the last version of blocked channels
                multiSelectListPreference.setEntries(getBlockedChannels());

                //selected names are the channels that user chooses
                //Object o gives us a set of blocked channel names
                Collection<String> selectedNames = (Collection<String>) o;
                for (String channel : selectedNames) {
                    blockedChannelsDb.remove(channel);
                }
                return true;
            }
        });
    }

    /**
     * Method to get updated version of blocked channels
     *
     * @return updated version of blocked channels.
     */
    private String[] getBlockedChannels() {
        final BlockedChannelsDb blockedChannelsDb = BlockedChannelsDb.getBlockedChannelsDb();
        return blockedChannelsDb.getBlockedChannelsListName().
                toArray(new String[blockedChannelsDb.getBlockedChannelsListName().size()]);
    }
```

**Comment by ram-on** [comment]
Hello @okan35, that fix works great.  

With respect to `BlockedChannelsPreferenceFragment`:  please delete lines 28 and 29 as that code is duplicate and defined in `getBlockedChannels()`.  Also remove any unnecessary logs.

A bug that I've noted is that if a user is subscribed to a channel and the user tried to blocked that channel, that channel's videos will still be listed in the Feed tab.  To solve this, just add an instruction to unsubscribe to the channel first, before the channel is blocked -- just call `SubscriptionsDb#unsubscribe()` -> you might need to overload that method (remember no code duplication pls!)

**Comment by okan35** [comment]
Do you mean something like this ? Like I should warn user to unsubscribe first. https://streamable.com/b6x51

By the way I do not understand usage of commented codes as those methods also work without those codes, aren't they just duplicate ?

```java
public boolean unsubscribe(YouTubeChannel channel) {
		/*getWritableDatabase().delete(SubscriptionsVideosTable.TABLE_NAME,
						SubscriptionsVideosTable.COL_CHANNEL_ID + " = ?",
						new String[]{channel.getId()});
*/
		int rowsDeleted = getWritableDatabase().delete(SubscriptionsTable.TABLE_NAME,
				SubscriptionsTable.COL_CHANNEL_ID + " = ?",
				new String[]{channel.getId()});

		return (rowsDeleted >= 0);
	}```

```java
public boolean remove(YouTubeVideo video) {
		/*getWritableDatabase().delete(BookmarksTable.TABLE_NAME,
						BookmarksTable.COL_YOUTUBE_VIDEO_ID + " = ?",
						new String[]{video.getId()});
*/
		int rowsDeleted = getWritableDatabase().delete(BookmarksTable.TABLE_NAME,
						BookmarksTable.COL_YOUTUBE_VIDEO_ID + " = ?",
						new String[]{video.getId()});
		boolean successful = false;

		if(rowsDeleted >= 0) {
			// Since we've removed a video, we will need to update the order column for all the videos.
			int order = 1;
			Cursor	cursor = getReadableDatabase().query(
							BookmarksTable.TABLE_NAME,
							new String[]{BookmarksTable.COL_YOUTUBE_VIDEO, BookmarksTable.COL_ORDER},
							null,
							null, null, null, BookmarksTable.COL_ORDER + " ASC");
			if(cursor.moveToNext()) {
				do {
					byte[] blob = cursor.getBlob(cursor.getColumnIndex(BookmarksTable.COL_YOUTUBE_VIDEO));
					YouTubeVideo uvideo = new Gson().fromJson(new String(blob), new TypeToken<YouTubeVideo>(){}.getType());
					ContentValues contentValues = new ContentValues();
					contentValues.put(BookmarksTable.COL_ORDER, order++);

					getWritableDatabase().update(BookmarksTable.TABLE_NAME, contentValues, BookmarksTable.COL_YOUTUBE_VIDEO_ID + " = ?",
									new String[]{uvideo.getId()});
				} while(cursor.moveToNext());
			}

			cursor.close();

			onUpdated();
			successful = true;
		}

		return successful;
	}```

**Comment by ram-on** [comment]
> I tried deleting and just using getBlockedChannels method.

That's the way to go -- commit it when you're ready

Regarding, the duplicate code in `SubscriptionsDb#unsubscribe()` and `BookmarkDb#remove()`:  that's actually a good catch - pls remove that code.

**Comment by okan35** [comment]
@ram-on I cleaned the duplicate codes and logs and pushed the changes.

**Comment by ram-on** [comment]
Looks great!  Thanks.

**Pull request merged**
