### PR TITLE
Channel search

### PR DESCRIPTION
**Pull request by okan35**
Hi @ram-on I finally finished the channel search feature. So now we have a `SearchView` next to `Subscriptions` textview and when clicked on it, this searchview disappears and opens other one under the `Subscriptions` textview but the problem is `onCloseListener` of `SearchView` is literally not working. From what I read it is a known bug so I had to go around for a solution. So I had fix this by using `onDrawerClosed` of subsDrawer, when the drawer is closed. The first searchview is iconified and the second one which we use for searching is gone. 

And when I cleaned data and imported channels from my youtube xml and made searches on it, it worked without a problem. 

By the way there were conflicts on `SubsAdapter.java` I fixed them by copying everything from my currently working class and pasting it on here.

Edit: It is not working as I want yet, gives problems when user clicks on a channel or subscribes a channel the list multiplies. :) Would be good to hear if you have suggestions for solution as I just wanted to apply this https://stackoverflow.com/questions/30398247/how-to-filter-a-recyclerview-with-a-searchview second short answer.

### CODE REVIEW

**Comment by okan35** [comment]
Oh I thought by working on different branches separately it would be easier for you. I can add it back

**Comment by okan35** [comment]
I will add it tomorrow and also work on this feature again as it just keeps working from some part and getting broken from other part.

**Comment by ram-on** [comment]
Before you do any pull request, pls make sure that your branches are based on my master branch.  Follow the guide:  https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by ram-on** [comment]
@okan35 Gentle reminder - branch still has conflicts.

**Comment by okan35** [comment]
@ram-on according to my tests the feature is working. It seems like it is fixed as I haven't had any problems so far with the last commit.

**Comment by ram-on** [comment]
@okan35 This code cannot even compile...  Pls fix it.

[Error 1](https://i.imgur.com/72E053x.png)
[Error 2](https://i.imgur.com/6YPq5Th.png)

**Comment by okan35** [comment]
@ram-on can you pls check now ?

**Comment by okan35** [comment]
I mean I committed after I tested, there were issues and I resolved them.

**Pull request closed without merging**
