### PR TITLE
subscription feed change from dialog to notification

### PR DESCRIPTION
**Pull request by okan35**

### CODE REVIEW

**Comment by okan35** [comment]
Hey guys I managed make a pull request, I had to get all the changes from master to my fork and just paste these changes to file and make a pull request. It is was working for me when I tried directly from a branch that was from ram-on's master. Hope it is good.

**Comment by gzsombor** [comment]
Thanks for the patch, unfortunately it doesn't compile, because it refers to the old android.support.v4.* packages, which were removed recently, when we migrated to androidx packages. Most likely, your IDE could fix the imports automatically.

**Comment by okan35** [comment]
Oh, I will try to fix it tomorrow.

**Comment by okan35** [comment]
I made a gradle upgrade, the only v4 import is this `import android.support.v4.app.NotificationCompat;` I am also updating android studio don't know if it will help. Please let me know if it does not help.

**Comment by atomjack** [comment]
@okan35 I suggest you start a new branch, off of the latest from upstream/master, and then manually redo your changes on it. Your original branch was super outdated, which is why the CI build failed, and this is just getting kinda messy.

**Comment by okan35** [comment]
Actually I did that but I wasn't sure how I would push from there so I tried to get all the changes to my fork which I tried to make totally up to date.

**Comment by atomjack** [comment]
You need to do this:
1) `git remote add upstream git@github.com:ram-on/SkyTube.git` (if you haven't already)
2) `git fetch upstream` (makes sure your system knows what the latest is on upstream)
3) `git checkout master` (you should now be in your fork's master branch)
4) `git merge upstream/master` (merge's any changes from upstream that your fork's master branch doesn't have)
5) `git checkout -b subsFetchNotifications` (create a new branch off of master, with a new name)

Then do your changes. If you push it up and the CI build fails, it's probably because your branch is missing new commits that had been merged into upstream/master (since you diverged from it). If you do step #2 again, then:
`git rebase upstream/master`, that will temporarily remove the commits you added to your branch since it diverged from upstream/master, update your branch with the latest from upstream/master, then re-apply your commits onto that. Note that when you do this, you have to do a force push when you push your branch back up to github:
`git push -f subsFetchNotifications`

**Comment by okan35** [comment]
Ok I will try it.

**Comment by okan35** [comment]
@gzsombor is it not possible for you to just copy and paste my code into your environment and if it is working,just have it for the next release ? I would like to have this feature very much in skytube but whenever I want to do something I have problems with git.

**Comment by gzsombor** [comment]
I could rebase it, and I'm going to test it, and merge before the next release! Thanks for the patch :+1:

**Pull request closed without merging**
