### PR TITLE
unsubscribe from all channels

### PR DESCRIPTION
**Pull request by okan35**
@ram-on Finished the feature for unsubscribing from all channels before importing youtube channels.

### CODE REVIEW

**Comment by ram-on** [comment]
Hello @okan35, I've tested this PR.  Please find my feedback below:

**Bug:**
1. Go to Preferences > Backups and tap "Import Subscriptions From YouTube"
1. Tick "Unsubscribe from all the channels"
1. Click Cancel and you'll see that all channels have been removed even though the user clicked cancel:  i.e. those channels should only be removed after the user clicks on "Import Subscriptions"


**Code Changes:**
* DB-related tasks (`unsubscribeFromAllChannelsTask`) should be placed under the package `free.rm.skytube.businessobjects.db.Tasks`
* Rename `unsubscribeFromAllChannelsTask` to `UnsubscribeFromAllChannelsTask` as per Java Coding Convention
* `SubscriptionsDb#Context` is not used and should be removed.
* Also, please do not change the order of the instance variables and constants (refer to `SubscriptionsDb` and  `SubscriptionsBackupsManager`):  this is as GitHub's diff tool will mark the whole file as changed and thus making it difficult to pin point the actual changes...
* As I've stated before, replace `e.printStackTrace()` with `Logger.e(this, "Error descriptions goes here", e);`
* Remove any changes from the following files as no actual change was made:
    * app/src/main/java/free/rm/skytube/gui/businessobjects/adapters/SubsAdapter.java
    * app/src/main/java/free/rm/skytube/gui/activities/YouTubePlayerActivity.java
    * app/src/main/java/free/rm/skytube/gui/businessobjects/adapters/SubsAdapter.java
    * app/src/main/java/free/rm/skytube/gui/fragments/BookmarksFragment.java

**Comment by okan35** [comment]
@ram-on I will fix all of them hopefully today. I thought wrong about the part for unsubscribing from all channels so it will be done if the user presses import subscriptions.

**Comment by okan35** [comment]
@ram-on I think I did the changes you requested. I am just not sure what I changed in those classes as I really did not change anything. Just maybe to make the code look better by removing/adding some spaces. 

I think I can't remove the `context` as it is connected `SubsAdapter` so it is in usage.

**Comment by ram-on** [comment]
Hi @okan35, the bug is still present:
1. Tap Import subscriptions from YouTube
1. Tick unsubscribe from all the channels
1. Tap Select File
1. Click cancel > All subscribed channels are removed.

Also go through each Java file changed and make sure that the indentation is doing in **tabs** (1 tab = 4 spaces) and not in spaces.  (This is while some files were marked as all changed).

**Comment by okan35** [comment]
@ram-on  I fixed the bug. When I tried to import the file from youtube and cancelled it, subscribed channels were still there which is good. And when I imported the file, all the channels were unsubscribed after checking the option.  I will check the changes you mentioned thoroughly.

**Comment by ram-on** [comment]
Great.

* Now go to app/src/main/java/free/rm/skytube/gui/businessobjects/SubscriptionsBackupsManager.java and change the indentation from 4 spaces to 1 tab.

* The following changes pertain to the Internet Checking PR, please remove them 9as they are in the other PR):
1. SkyTubeApp.java
1. MainActivity.java

* Remove any changes from the following files as no actual change were made:
1.   app/src/main/java/free/rm/skytube/gui/activities/YouTubePlayerActivity.java
1.   app/src/main/java/free/rm/skytube/gui/businessobjects/adapters/GridViewHolder.java
1.   app/src/main/java/free/rm/skytube/gui/businessobjects/adapters/SubsAdapter.java
1.    app/src/main/java/free/rm/skytube/gui/fragments/BookmarksFragment.java
1.  app/src/main/java/free/rm/skytube/gui/fragments/YouTubePlayerFragment.java

**Comment by okan35** [comment]
@ram-on  I think I hopefully did indentation change. If you can please check and let me know.

**Comment by ram-on** [comment]
That looks good - pls repeat that process for **SubscriptionsDb** (1 tab = 4 spaces).

Also, the following changes pertain to the Internet Checking PR, please remove them as they are in the other PR):
1.  SkyTubeApp.java
2.  MainActivity.java

Remove any changes from the following files as no actual change were made
1. app/src/main/java/free/rm/skytube/gui/activities/YouTubePlayerActivity.java
2. app/src/main/java/free/rm/skytube/gui/businessobjects/adapters/GridViewHolder.java
3. app/src/main/java/free/rm/skytube/gui/businessobjects/adapters/SubsAdapter.java
4. app/src/main/java/free/rm/skytube/gui/fragments/BookmarksFragment.java
5. app/src/main/java/free/rm/skytube/gui/fragments/YouTubePlayerFragment.java

**Comment by okan35** [comment]
I also did indentation change for that file. But I am not sure how to remove unreal changes from those files. Like do I need to compare them on github and delete some part or reverse the commit ?

**Comment by okan35** [comment]
@ram-on  I think it can be better to make another pull requests for these two features. Unsubscribe-all and check internet with null pointer fix that was caused by not working connection. 

If you think it is easier I can just copy and paste the changes and just commit the files that I will change, nothing else. So it will be easier and cleaner. What do you think ?

**Comment by ram-on** [comment]
I prefer to have these two PR separate.  Maybe you can close these 2 PR and one 2 new ones in which only the actual changes are committed?  What do you think?

**Comment by okan35** [comment]
Yeah that is what I want and find easier.I will close these  two PRs and I will make two new PRs as unsubscribe-all-new and connection-check-new and I will just commit and push the files I changed. This is the best and easiest solution in my opinion as I messed the branches and commits before.

**Comment by ram-on** [comment]
Sounds great!

**Pull request closed without merging**
