### PR TITLE
Use AndroidX Preference.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**

### CODE REVIEW

**Comment by gzsombor** [comment]
Looks nice, I've found only one problem, previously, if you clicked on the back arrow on the main preference page, we went back to the MainActivity, now, nothing happens.
And a couple of questions:
1, Why the special handling of the VideoBlockerPreferenceFragment ? Is it because we want to directly navigate to that fragment? 
2, Is there any changes in AndroidManifest.xml, or it was just an un-intentional whitespace/reformat change, probably by IntelliJ?

**Comment by Isira-Seneviratne** [comment]
> Looks nice, I've found only one problem, previously, if you clicked on the back arrow on the main preference page, we went back to the MainActivity, now, nothing happens.
> And a couple of questions:
> 1, Why the special handling of the VideoBlockerPreferenceFragment ? Is it because we want to directly navigate to that fragment?

Yeah.

> 2, Is there any changes in AndroidManifest.xml, or it was just an un-intentional whitespace/reformat change, probably by IntelliJ?

Yeah, I created the settings activity using Android Studio's activity creation wizard, which caused it to update the manifest.

**Comment by gzsombor** [comment]
I've just finished testing your other change, and merged your code - so this will have merge conflicts :(

**Comment by Isira-Seneviratne** [comment]
> I've just finished testing your other change, and merged your code - so this will have merge conflicts :(

I fixed those.

**Comment by gzsombor** [comment]
Thanks for the patch!

**Pull request merged**
