### PR TITLE
Use the Java 8 Date/Time API.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
Switch from Joda-Time to the [`java.time`](https://developer.android.com/reference/java/time/package-summary) package, as the latter is [recommended](https://www.joda.org/joda-time/) over Joda-Time.

### CODE REVIEW

**Comment by gzsombor** [comment]
Thanks for the patch, it looks good in itself, however there is an ugly problem inside SkyTube, is that inside the subscription db, it stores the video information as JSON too, and if we apply your changes, and if someone has a non-empty database, the app will break with an exception like this:
```
java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.RuntimeException: Failed to invoke j$.time.ZoneId() with no args
       at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:113)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:897)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.google.gson.Gson.fromJson(Gson.java:817)
       at free.rm.skytube.businessobjects.db.SubscriptionsDb.extractVideos(SubscriptionsDb.java:656)
       at free.rm.skytube.businessobjects.db.SubscriptionsDb.getSubscriptionVideoPage(SubscriptionsDb.java:617)
       at free.rm.skytube.businessobjects.db.SubscriptionsDb.getSubscriptionVideoPage(SubscriptionsDb.java:593)
       at free.rm.skytube.businessobjects.db.Tasks.GetSubscriptionsVideosFromDb.getNextVideos(GetSubscriptionsVideosFromDb.java:47)
       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.collectUntil(GetYouTubeVideosTask.java:135)
       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.getNextVideos(GetYouTubeVideosTask.java:125)
       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:102)
       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:43)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       ... 3 more
Caused by: java.lang.InstantiationException: Can't instantiate abstract class j$.time.ZoneId
       at java.lang.reflect.Constructor.newInstance(Native Method)
       at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:110)

```  
As the publish timestamp is already saved in json - and even in as a separate column, I don't think we need to parse that field  from that json anymore - so one solution would be to configure Gson somehow to avoid that field....

**Comment by Isira-Seneviratne** [comment]
> Thanks for the patch, it looks good in itself, however there is an ugly problem inside SkyTube, is that inside the subscription db, it stores the video information as JSON too, and if we apply your changes, and if someone has a non-empty database, the app will break with an exception like this:
> 
> ```
> java.lang.RuntimeException: An error occurred while executing doInBackground()
>        at android.os.AsyncTask$3.done(AsyncTask.java:309)
>        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
>        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
>        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
>        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
>        at java.lang.Thread.run(Thread.java:818)
> Caused by: java.lang.RuntimeException: Failed to invoke j$.time.ZoneId() with no args
>        at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:113)
>        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:212)
>        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
>        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
>        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
>        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
>        at com.google.gson.Gson.fromJson(Gson.java:932)
>        at com.google.gson.Gson.fromJson(Gson.java:897)
>        at com.google.gson.Gson.fromJson(Gson.java:846)
>        at com.google.gson.Gson.fromJson(Gson.java:817)
>        at free.rm.skytube.businessobjects.db.SubscriptionsDb.extractVideos(SubscriptionsDb.java:656)
>        at free.rm.skytube.businessobjects.db.SubscriptionsDb.getSubscriptionVideoPage(SubscriptionsDb.java:617)
>        at free.rm.skytube.businessobjects.db.SubscriptionsDb.getSubscriptionVideoPage(SubscriptionsDb.java:593)
>        at free.rm.skytube.businessobjects.db.Tasks.GetSubscriptionsVideosFromDb.getNextVideos(GetSubscriptionsVideosFromDb.java:47)
>        at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.collectUntil(GetYouTubeVideosTask.java:135)
>        at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.getNextVideos(GetYouTubeVideosTask.java:125)
>        at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:102)
>        at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:43)
>        at android.os.AsyncTask$2.call(AsyncTask.java:295)
>        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>        ... 3 more
> Caused by: java.lang.InstantiationException: Can't instantiate abstract class j$.time.ZoneId
>        at java.lang.reflect.Constructor.newInstance(Native Method)
>        at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:110)
> ```
> 
> As the publish timestamp is already saved in json - and even in as a separate column, I don't think we need to parse that field from that json anymore - so one solution would be to configure Gson somehow to avoid that field....

There's an adapter for `java.time`: https://github.com/gkopff/gson-javatime-serialisers

**Comment by gzsombor** [comment]
That could work in a long term, however, the current problem is that, inside the db, everyone have this very badly serialized DateTime objects, so we need to ensure, that when we try to read that json, we don't get exceptions. (As we already store the timestamp at least once in the json, and once in another column, we could even somehow skip reading that field totally.

The current json is something like this:
```
{
  "channel": {
    "id": "xxxxxxxxxxxxxx",
    "title": "xxx",
    "description": "xxxx.",
    "thumbnailNormalUrl": "xxxxxx",
    "bannerUrl": "xxxxxx"
  },
  "dislikeCountNumber": 9,
  "duration": "34:46",
  "durationInSeconds": 2086,
  "isLiveStream": false,
  "likeCountNumber": 733,
  "publishDate": {
    "dateTime": {
      "date": {
        "day": 1,
        "month": 12,
        "year": 2020
      },
      "time": {
        "hour": 1,
        "minute": 0,
        "nano": 0,
        "second": 0
      }
    },
    "offset": {
      "totalSeconds": 3600
    },
    "zone": {
      "id": "Europe/Budapest"
    }
  },
  "retrievalTimestamp": 1607029481677,
  "thumbnailMaxResUrl": "aaaaaaaaaaaaaaaaa",
  "thumbsUpPercentage": 99,
  "viewsCount": "8,712 views",
  "viewsCountInt": 8712,
  "description": "aaaaaaaaaaa",
  "id": "aaaaaaaaaaaaaaaaa",
  "publishTimestamp": 1606852809000,
  "publishTimestampExact": true,
  "thumbnailUrl": "xxxx",
  "title": "yyyyyy"
}

```

Maybe, if we just create a 'VideoData' class, with just the important field, and read it with Gson as before, that would fix the compatibility problem.

**Comment by Isira-Seneviratne** [comment]
> That could work in a long term, however, the current problem is that, inside the db, everyone have this very badly serialized DateTime objects, so we need to ensure, that when we try to read that json, we don't get exceptions. (As we already store the timestamp at least once in the json, and once in another column, we could even somehow skip reading that field totally.
> 
> The current json is something like this:
> 
> ```
> {
>   "channel": {
>     "id": "xxxxxxxxxxxxxx",
>     "title": "xxx",
>     "description": "xxxx.",
>     "thumbnailNormalUrl": "xxxxxx",
>     "bannerUrl": "xxxxxx"
>   },
>   "dislikeCountNumber": 9,
>   "duration": "34:46",
>   "durationInSeconds": 2086,
>   "isLiveStream": false,
>   "likeCountNumber": 733,
>   "publishDate": {
>     "dateTime": {
>       "date": {
>         "day": 1,
>         "month": 12,
>         "year": 2020
>       },
>       "time": {
>         "hour": 1,
>         "minute": 0,
>         "nano": 0,
>         "second": 0
>       }
>     },
>     "offset": {
>       "totalSeconds": 3600
>     },
>     "zone": {
>       "id": "Europe/Budapest"
>     }
>   },
>   "retrievalTimestamp": 1607029481677,
>   "thumbnailMaxResUrl": "aaaaaaaaaaaaaaaaa",
>   "thumbsUpPercentage": 99,
>   "viewsCount": "8,712 views",
>   "viewsCountInt": 8712,
>   "description": "aaaaaaaaaaa",
>   "id": "aaaaaaaaaaaaaaaaa",
>   "publishTimestamp": 1606852809000,
>   "publishTimestampExact": true,
>   "thumbnailUrl": "xxxx",
>   "title": "yyyyyy"
> }
> ```
> 
> Maybe, if we just create a 'VideoData' class, with just the important field, and read it with Gson as before, that would fix the compatibility problem.

Or maybe a custom adapter could be defined?

**Comment by gzsombor** [comment]
Yes, that could work too, maybe it's simpler. Somehow we need to separate the in-memory object from the persisted json, because this makes any refactoring painful.

**Comment by gzsombor** [comment]
Sorry, but your code still doesn't handle the old jsons properly, if I start this code in an emulator - with an already existing subscription, I get this:
```
 SubscriptionsDb: java.lang.UnsupportedOperationException: JsonObject
 SubscriptionsDb:       at com.google.gson.JsonElement.getAsLong(JsonElement.java:218)
 SubscriptionsDb:       at free.rm.skytube.businessobjects.db.gson.ZonedDateTimeDeserializer.deserialize(ZonedDateTimeDeserializer.java:31)
 SubscriptionsDb:       at free.rm.skytube.businessobjects.db.gson.ZonedDateTimeDeserializer.deserialize(ZonedDateTimeDeserializer.java:28)
 SubscriptionsDb:       at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
 SubscriptionsDb:       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
 SubscriptionsDb:       at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
 SubscriptionsDb:       at com.google.gson.Gson.fromJson(Gson.java:932)
 SubscriptionsDb:       at com.google.gson.Gson.fromJson(Gson.java:897)
 SubscriptionsDb:       at com.google.gson.Gson.fromJson(Gson.java:846)
 SubscriptionsDb:       at com.google.gson.Gson.fromJson(Gson.java:817)
 SubscriptionsDb:       at free.rm.skytube.businessobjects.db.SubscriptionsDb.extractVideos(SubscriptionsDb.java:656)
 SubscriptionsDb:       at free.rm.skytube.businessobjects.db.SubscriptionsDb.getSubscriptionVideoPage(SubscriptionsDb.java:620)
 SubscriptionsDb:       at free.rm.skytube.businessobjects.db.SubscriptionsDb.getSubscriptionVideoPage(SubscriptionsDb.java:596)
 SubscriptionsDb:       at free.rm.skytube.businessobjects.db.Tasks.GetSubscriptionsVideosFromDb.getNextVideos(GetSubscriptionsVideosFromDb.java:47)
 SubscriptionsDb:       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.collectUntil(GetYouTubeVideosTask.java:133)
 SubscriptionsDb:       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.getNextVideos(GetYouTubeVideosTask.java:123)
 SubscriptionsDb:       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:100)
 SubscriptionsDb:       at free.rm.skytube.businessobjects.YouTube.Tasks.GetYouTubeVideosTask.doInBackground(GetYouTubeVideosTask.java:43)
 SubscriptionsDb:       at android.os.AsyncTask$2.call(AsyncTask.java:295)
 SubscriptionsDb:       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 SubscriptionsDb:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
 SubscriptionsDb:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
 SubscriptionsDb:       at java.lang.Thread.run(Thread.java:818)

```

As we still don't need that ZonedDateTime field, as there is already a timestamp for that value, I'm more and more think that the simplest would be to avoid loading this field from the db (and avoid writing too)

**Comment by gzsombor** [comment]
Thanks, it looks it is working now, I'm going to merge it.

**Comment by gzsombor** [comment]
Ohh, I've screwed up the merge. Next try, locally...

**Comment by gzsombor** [comment]
Thanks @Isira-Seneviratne for the patch, I've rebased and merged your code!

**Pull request closed without merging**
