### PR TITLE
Play-video-externally should work on the downloaded file

### PR DESCRIPTION
**Pull request by gzsombor**

### CODE REVIEW

**Comment by ram-on** [comment]
Hi @gzsombor, I'm getting an exception when trying to open a downloaded video externally:

```
08-07 20:40:45.149 9346-9346/free.rm.skytube.oss E/AndroidRuntime: FATAL EXCEPTION: main
    Process: free.rm.skytube.oss, PID: 9346
    android.os.FileUriExposedException: file:///storage/emulated/0/Movies/BphwqL3rStQ.mp4 exposed beyond app through Intent.getData()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
        at android.net.Uri.checkFileUriExposed(Uri.java:2356)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9766)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1609)
        at android.app.Activity.startActivityForResult(Activity.java:4472)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4430)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at android.app.Activity.startActivity(Activity.java:4791)
        at android.app.Activity.startActivity(Activity.java:4759)
        at free.rm.skytube.businessobjects.YouTube.POJOs.YouTubeVideo.playVideoExternally(YouTubeVideo.java:542)
        at free.rm.skytube.gui.businessobjects.adapters.GridViewHolder$4.onMenuItemClick(GridViewHolder.java:213)
        at android.support.v7.widget.PopupMenu$1.onMenuItemSelected(PopupMenu.java:112)
        at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
        at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
        at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
        at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1165)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3134)
        at android.widget.AbsListView$3.run(AbsListView.java:4049)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by atomjack** [comment]
A quick googling came up with this solution: https://stackoverflow.com/questions/38200282/android-os-fileuriexposedexception-file-storage-emulated-0-test-txt-exposed

**Comment by gzsombor** [comment]
Interesting, I tried in emulator running 4.4.2 and my tablet, running 6.0, and it worked, however the targetSdkVersion is 27, so it shoudn't work in my environment neither.

**Comment by ram-on** [comment]
Confirmed to be working.  Thx

**Pull request merged**
