### PR TITLE
Code cleanup and updates

### PR DESCRIPTION
**Pull request by TacoTheDank**
Sorry this is kinda big.

### 1st commit
- Update gradle wrapper to 6.6.1 using git bash

### 2nd commit
- Update Android Studio 4.0.0 -> 4.0.1
- Update buildTools 29.0.2 -> 29.0.3
- Update google-api-services-youtube v3-rev20200312-1.30.9 -> v3-rev20200423-1.30.9 (no important changes between these)
- Update Glide 4.10.0 -> 4.11.0 ([changelog](https://github.com/bumptech/glide/releases))
- Update Material-Dialogs 0.9.5.0 -> 0.9.6.0 ([changelog](https://github.com/afollestad/material-dialogs/releases?after=2.0.0-alpha10))
- Update play-services-cast-framework 18.1.0 -> 19.0.0 ([changelog](https://developers.google.com/cast/docs/release-notes#august-3,-2020))
- Update Picasso 2.5.2 -> 2.71828 (there's not really a changelog)
- Remove unneeded libraries

### 3th commit
- Fix some deprecations

### 4th commit
- Update AppCompat 1.1.0 -> 1.2.0 ([changelog](https://developer.android.com/jetpack/androidx/releases/appcompat))
- Update Material 1.2.0 -> 1.2.1 ([changelog](https://github.com/material-components/material-components-android/releases))
- Update Core 1.2.0 -> 1.3.1 ([changelog](https://developer.android.com/jetpack/androidx/releases/core))

### 5th-13th commits
- Fixed various lints throughout the codebase

### 14th commit
- Delete unused tests

### CODE REVIEW

**Comment by gzsombor** [comment]
First, thanks for the patches, generally it makes sense, and looks good.
 However, it looks, that these change introduce a crash during opening the preference page:

```
AndroidRuntime: Process: free.rm.skytube.oss, PID: 3284
AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{free.rm.skytube.oss/free.rm.skytube.gui.activities.PreferencesActivity}: android.app.Fragment$InstantiationException: Trying to instantiate a class free.rm.skytube.gui.fragments.preferences.AboutPreferenceFragment that is not a Fragment
AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5417)
AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
AndroidRuntime: Caused by: android.app.Fragment$InstantiationException: Trying to instantiate a class free.rm.skytube.gui.fragments.preferences.AboutPreferenceFragment that is not a Fragment
AndroidRuntime:        at android.app.Fragment.instantiate(Fragment.java:608)
AndroidRuntime:        at android.preference.PreferenceActivity.switchToHeaderInner(PreferenceActivity.java:1226)
AndroidRuntime:        at android.preference.PreferenceActivity.switchToHeader(PreferenceActivity.java:1249)
AndroidRuntime:        at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:586)
AndroidRuntime:        at free.rm.skytube.gui.businessobjects.preferences.ActionBarPreferenceActivity.onCreate(ActionBarPreferenceActivity.java:71)
AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6237)
AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
AndroidRuntime:        ... 9 more
AndroidRuntime: Caused by: java.lang.ClassCastException
AndroidRuntime:        at android.app.Fragment.instantiate(Fragment.java:609)

```

And adding that lot's of non-null checks also looks a bit strange. Why do you need to do that?

**Comment by TacoTheDank** [comment]
@gzsombor A bunch of methods in AndroidX Preference become nullable, so it's to prevent null exceptions.

Anyway, I'll just undo the AndroidX preference migration, since the problem lies with the deprecated PreferenceActivity that idk how exactly to replace.

**Comment by TacoTheDank** [comment]
@gzsombor I had to fix some weird unresolved error by migrating BackupPreferenceFragment to AndroidX preference. I don't have the means to test stuff right now. Could you test this fragment for me and see if everything works fine?

**Comment by gzsombor** [comment]
You should start using the android emulator, it's not that complicated :wink: 
I've checked, and it fails similarly, as your last attempt:
```
 java.lang.RuntimeException: Unable to start activity ComponentInfo{free.rm.skytube.oss/free.rm.skytube.gui.activities.PreferencesActivity}: android.app.Fragment$InstantiationException: Trying to instantiate a class free.rm.skytube.gui.fragments.preferences.BackupPreferenceFragment that is not a Fragment
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: android.app.Fragment$InstantiationException: Trying to instantiate a class free.rm.skytube.gui.fragments.preferences.BackupPreferenceFragment that is not a Fragment
        at android.app.Fragment.instantiate(Fragment.java:608)
        at android.preference.PreferenceActivity.switchToHeaderInner(PreferenceActivity.java:1226)
        at android.preference.PreferenceActivity.switchToHeader(PreferenceActivity.java:1249)
        at android.preference.PreferenceActivity.onCreate(PreferenceActivity.java:586)
        at free.rm.skytube.gui.businessobjects.preferences.ActionBarPreferenceActivity.onCreate(ActionBarPreferenceActivity.java:71)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        ... 9 more
 Caused by: java.lang.ClassCastException
        at android.app.Fragment.instantiate(Fragment.java:609)
        ... 16 more
```

What about skipping this refactor? I still thinks, if findPreferences returns null, that is a programmer error, and would rather not see a half-working - so confusing - preference page

**Comment by TacoTheDank** [comment]
@gzsombor Figured that would happen. The problem is with PreferenceActivity, which is severely deprecated and does not work properly with Preference compat classes. It needs to be replaced ASAP.

I'll skip it, as that's the best option at this point.

**Comment by TacoTheDank** [comment]
@gzsombor Everything should be good now.

**Comment by gzsombor** [comment]
Thanks for the patch, this makes a code a bit better :+1: 

sorry for the delays!

**Comment by TacoTheDank** [comment]
Thanks!

**Pull request merged**
